CREATE ROLE ravana WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:3uCgwEJKPn4YC/EGa3DaiA==$kWJ2c1Ja+JFSruqTStwNY1SQDsYrPSN8Ia8ebwfN2og=:d4aIlAiYsyVQzL0AqbewY/yxXx6gIQdXgMX8/MAoxrI=';
GRANT ALL ON DATABASE ravana TO ravana;